# https://github.com/ianyh/Amethyst/blob/development/.amethyst.sample.yml
layouts:
  - fullscreen
  - tall

mod1:
  - option
  - shift
mod2:
  - control
  - option
  - shift

cycle-layout-backward:
  mod: <NONE>
  key: <NONE>
cycle-layout:
  mod: mod1
  key: space
decrease-main:
  mod: <NONE>
  key: <NONE>
display-current-layout:
  mod: <NONE>
  key: <NONE>
expand-main:
  mod: mod1
  key: l
focus-ccw:
  mod: <NONE>
  key: <NONE>
focus-cw:
  mod: <NONE>
  key: <NONE>
focus-main:
  mod: <NONE>
  key: <NONE>
focus-screen-1:
  mod: <NONE>
  key: <NONE>
focus-screen-2:
  mod: <NONE>
  key: <NONE>
focus-screen-3:
  mod: <NONE>
  key: <NONE>
focus-screen-4:
  mod: <NONE>
  key: <NONE>
focus-screen-ccw:
  mod: <NONE>
  key: <NONE>
focus-screen-cw:
  mod: <NONE>
  key: <NONE>
focus-space-10:
  mod: <NONE>
  key: <NONE>
focus-space-1:
  mod: <NONE>
  key: <NONE>
focus-space-2:
  mod: <NONE>
  key: <NONE>
focus-space-3:
  mod: <NONE>
  key: <NONE>
focus-space-4:
  mod: <NONE>
  key: <NONE>
focus-space-5:
  mod: <NONE>
  key: <NONE>
focus-space-6:
  mod: <NONE>
  key: <NONE>
focus-space-7:
  mod: <NONE>
  key: <NONE>
focus-space-8:
  mod: <NONE>
  key: <NONE>
focus-space-9:
  mod: <NONE>
  key: <NONE>
increase-main:
  mod: <NONE>
  key: <NONE>
reevaluate-windows:
  mod: <NONE>
  key: <NONE>
relaunch-amethyst:
  mod: mod1
  key: q
select-column-layout:
  mod: <NONE>
  key: <NONE>
select-fullscreen-layout:
  mod: <NONE>
  key: <NONE>
select-tall-layout:
  mod: <NONE>
  key: <NONE>
select-wide-layout:
  mod: <NONE>
  key: <NONE>
shrink-main:
  mod: mod1
  key: h
swap-ccw:
  mod: mod2
  key: k
swap-cw:
  mod: mod2
  key: j
swap-main:
  mod: mod1
  key: enter
swap-screen-ccw:
  mod: <NONE>
  key: <NONE>
swap-screen-cw:
  mod: <NONE>
  key: <NONE>
throw-screen-1:
  mod: <NONE>
  key: <NONE>
throw-screen-2:
  mod: <NONE>
  key: <NONE>
throw-screen-3:
  mod: <NONE>
  key: <NONE>
throw-screen-4:
  mod: <NONE>
  key: <NONE>
throw-space-10:
  mod: <NONE>
  key: <NONE>
throw-space-1:
  mod: <NONE>
  key: <NONE>
throw-space-2:
  mod: <NONE>
  key: <NONE>
throw-space-3:
  mod: <NONE>
  key: <NONE>
throw-space-4:
  mod: <NONE>
  key: <NONE>
throw-space-5:
  mod: <NONE>
  key: <NONE>
throw-space-6:
  mod: <NONE>
  key: <NONE>
throw-space-7:
  mod: <NONE>
  key: <NONE>
throw-space-8:
  mod: <NONE>
  key: <NONE>
throw-space-9:
  mod: <NONE>
  key: <NONE>
throw-space-left:
  mod: mod1
  key: p
throw-space-right:
  mod: mod1
  key: n
toggle-float:
  mod: <NONE>
  key: <NONE>
toggle-focus-follows-mouse:
  mod: <NONE>
  key: <NONE>
toggle-tiling:
  mod: <NONE>
  key: <NONE>

debug-layout-info: false
disable-screen-padding-on-inbuilt: false
enables-layout-hud-on-space-change: false
enables-layout-hud: false
float-small-windows: true
floating-is-blacklist: true
floating: [] # ["com.github.wez.wezterm"]
focus-follows-mouse: false
follow-space-thrown-windows: true
ignore-menu-bar: false
mouse-follows-focus: true
mouse-resizes-windows: false
mouse-swaps-windows: false
new-windows-to-main: false
restore-layouts-on-launch: true
screen-padding-bottom: 0
screen-padding-left: 0
screen-padding-right: 0
screen-padding-top: 0
smart-window-margins: false
use-canary-build: false
window-margin-size: 8
window-margins: true
window-max-count: 0
window-minimum-height: 0
window-minimum-width: 0
window-resize-step: 5
