tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "bat"
brew "efm-langserver"
brew "exa"
brew "fd"
brew "gh"
brew "gnutls"
brew "gnupg"
brew "htop"
brew "lua-language-server"
brew "luajit", args: ["HEAD"]
brew "tree-sitter", args: ["HEAD"]
brew "neovim", args: ["HEAD"]
brew "node@16"
brew "pinentry-mac"
brew "ripgrep"
brew "tmux"
brew "tree"
cask "alacritty"
cask "amethyst"
cask "font-iosevka-nerd-font"
